// <auto-generated />
using AP.DemoProject.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.DemoProject.Infrastructure.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20250919100251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.DemoProject.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CountryId = -1,
                            Name = "Antwerpen",
                            Population = 1000000
                        },
                        new
                        {
                            Id = -2,
                            CountryId = -1,
                            Name = "Brussel",
                            Population = 1500000
                        },
                        new
                        {
                            Id = -3,
                            CountryId = -2,
                            Name = "Paris",
                            Population = 6500000
                        },
                        new
                        {
                            Id = -4,
                            CountryId = -2,
                            Name = "Lille",
                            Population = 750000
                        },
                        new
                        {
                            Id = -5,
                            CountryId = -3,
                            Name = "Amsterdam",
                            Population = 2300000
                        },
                        new
                        {
                            Id = -6,
                            CountryId = -3,
                            Name = "Breda",
                            Population = 12500
                        });
                });

            modelBuilder.Entity("AP.DemoProject.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = -2,
                            Name = "France"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Netherlands"
                        });
                });

            modelBuilder.Entity("AP.DemoProject.Domain.City", b =>
                {
                    b.HasOne("AP.DemoProject.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
