// <auto-generated />
using AP.BTP.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.DemoProject.Infrastructure.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.DemoProject.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CountryId = -1,
                            Name = "Antwerpen",
                            Population = 1000000
                        },
                        new
                        {
                            Id = -2,
                            CountryId = -1,
                            Name = "Brussel",
                            Population = 1500000
                        },
                        new
                        {
                            Id = -3,
                            CountryId = -2,
                            Name = "Paris",
                            Population = 6500000
                        },
                        new
                        {
                            Id = -4,
                            CountryId = -2,
                            Name = "Lille",
                            Population = 750000
                        },
                        new
                        {
                            Id = -5,
                            CountryId = -3,
                            Name = "Amsterdam",
                            Population = 2300000
                        },
                        new
                        {
                            Id = -6,
                            CountryId = -3,
                            Name = "Breda",
                            Population = 12500
                        },
                        new
                        {
                            Id = -7,
                            CountryId = -1,
                            Name = "Gent",
                            Population = 800000
                        },
                        new
                        {
                            Id = -8,
                            CountryId = -1,
                            Name = "Brugge",
                            Population = 300000
                        },
                        new
                        {
                            Id = -9,
                            CountryId = -1,
                            Name = "Leuven",
                            Population = 200000
                        },
                        new
                        {
                            Id = -10,
                            CountryId = -1,
                            Name = "Namur",
                            Population = 150000
                        },
                        new
                        {
                            Id = -11,
                            CountryId = -1,
                            Name = "Liège",
                            Population = 500000
                        },
                        new
                        {
                            Id = -12,
                            CountryId = -2,
                            Name = "Marseille",
                            Population = 3000000
                        },
                        new
                        {
                            Id = -13,
                            CountryId = -2,
                            Name = "Lyon",
                            Population = 2000000
                        },
                        new
                        {
                            Id = -14,
                            CountryId = -2,
                            Name = "Toulouse",
                            Population = 1200000
                        },
                        new
                        {
                            Id = -15,
                            CountryId = -2,
                            Name = "Nice",
                            Population = 900000
                        },
                        new
                        {
                            Id = -16,
                            CountryId = -2,
                            Name = "Nantes",
                            Population = 600000
                        },
                        new
                        {
                            Id = -17,
                            CountryId = -2,
                            Name = "Bordeaux",
                            Population = 850000
                        },
                        new
                        {
                            Id = -18,
                            CountryId = -2,
                            Name = "Strasbourg",
                            Population = 750000
                        },
                        new
                        {
                            Id = -19,
                            CountryId = -2,
                            Name = "Montpellier",
                            Population = 700000
                        },
                        new
                        {
                            Id = -20,
                            CountryId = -3,
                            Name = "Rotterdam",
                            Population = 2000000
                        },
                        new
                        {
                            Id = -21,
                            CountryId = -3,
                            Name = "The Hague",
                            Population = 1800000
                        },
                        new
                        {
                            Id = -22,
                            CountryId = -3,
                            Name = "Utrecht",
                            Population = 1200000
                        },
                        new
                        {
                            Id = -23,
                            CountryId = -3,
                            Name = "Eindhoven",
                            Population = 900000
                        },
                        new
                        {
                            Id = -24,
                            CountryId = -3,
                            Name = "Groningen",
                            Population = 400000
                        },
                        new
                        {
                            Id = -25,
                            CountryId = -3,
                            Name = "Maastricht",
                            Population = 300000
                        },
                        new
                        {
                            Id = -26,
                            CountryId = -3,
                            Name = "Tilburg",
                            Population = 350000
                        },
                        new
                        {
                            Id = -27,
                            CountryId = -3,
                            Name = "Leiden",
                            Population = 250000
                        },
                        new
                        {
                            Id = -28,
                            CountryId = -3,
                            Name = "Delft",
                            Population = 150000
                        },
                        new
                        {
                            Id = -29,
                            CountryId = -3,
                            Name = "Zwolle",
                            Population = 180000
                        },
                        new
                        {
                            Id = -30,
                            CountryId = -3,
                            Name = "Arnhem",
                            Population = 250000
                        });
                });

            modelBuilder.Entity("AP.DemoProject.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = -2,
                            Name = "France"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Netherlands"
                        });
                });

            modelBuilder.Entity("AP.DemoProject.Domain.City", b =>
                {
                    b.HasOne("AP.DemoProject.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
